import { StyleSheet } from 'react-native';
import { RFPercentage } from 'react-native-responsive-fontsize';

export const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#CBEFD5',
    },
    containerHeader: {
        backgroundColor: '#A3E8AE',
    },
    header: {
        backgroundColor: '#4EC160',
        height: 164,
        borderBottomLeftRadius: 15,
        borderBottomRightRadius: 15,
    },
    textHeader: {
        fontSize: RFPercentage(6),
        color: 'white',
        fontFamily: 'Quicksand',
        textAlign: 'center',
    },
    menuButton: {
        backgroundColor: 'black',
        borderRadius: 70,
        width: 50,
        height: 50,
        justifyContent: 'center',
        alignItems: 'center',
    },
    containerEmotion: {
        backgroundColor: '#004A2B',
        borderRadius: 80,
        width: 60,
        height: 60,
        justifyContent: 'center',
        alignItems: 'center',
        marginLeft: 10,
        zIndex: 1,
    },
    emotion: {
        backgroundColor: '#99fa9d',
        borderRadius: 60,
        width: 50,
        height: 50,
        justifyContent: 'center',
        alignItems: 'center',
        marginLeft: 20,
        zIndex: 1,
        position: 'absolute',
    },
    containerBarEmotion: {
        backgroundColor: '#004A2B',
        borderTopRightRadius: 60,
        borderBottomRightRadius: 60,
        width: 250,
        height: 35,
        justifyContent: 'center',
        alignItems: 'right',
        marginLeft: -10,
    },
    barEmotion: {
        backgroundColor: '#5BF586',
        borderTopRightRadius: 60,
        borderBottomRightRadius: 60,
        height: 25,
        justifyContent: 'center',
        alignItems: 'center',
        marginLeft: -10,
    },
    containerInfo: {
        backgroundColor: '#A3E8AE',
        height: 105,
        borderBottomLeftRadius: 15,
        borderBottomRightRadius: 15,
        justifyContent: 'center',
        alignItems: 'center',
    },
    information: {
        width: '95%',
        height: 70,
        backgroundColor: '#CBF9CD',
        borderRadius: 20,
        justifyContent: 'center',
        alignItems: 'center',
        flexDirection: 'row',
        gap: 40,
    },
    containerMonedas: {
        width: 90,
        height: 34,
        backgroundColor: '#4EC160',
        borderRadius: 20,
        justifyContent: 'flex-start',
        alignItems: 'center',
        flexDirection: 'row',
    },
    monedas: {
        width: 40,
        height: 40,
        borderRadius: 20,
        backgroundColor: 'orange',
    },
    textMonedas: {
        color: 'white',
        fontSize: 15,
        fontFamily: 'Quicksand_SemiBold',
        marginLeft: 5,
    },
    containerLevel: {
        width: 50,
        height: 50,
        borderRadius: 25,
        backgroundColor: '#7fcc97',
        justifyContent: 'center',
        alignItems: 'center',
    },
    level: {
        width: 43,
        height: 43,
        borderRadius: 21,
        backgroundColor: '#398F53',
        justifyContent: 'center',
        alignItems: 'center',
    },
    textLevel: {
        color: 'white',
        fontSize: 20,
        fontFamily: 'Quicksand_SemiBold',
    },
    containerVictorias: {
        justifyContent: 'center',
        alignItems: 'center',
        flexDirection: 'row',
    },
    victorias: {
        justifyContent: 'center',
        alignItems: 'center',
    },
    imageWins: {
        width: 30,
        height: 30,
    },
    textVictorias: {
        color: 'black',
        fontSize: 15,
        fontFamily: 'Quicksand_SemiBold',
    },
    scrollArea: {
        flex: 1,
        marginBottom: 18,
        backgroundColor: '#CBEFD5',
    },
    scrollContainer: {
        marginTop: 20,
        paddingHorizontal: 10,
        paddingBottom: 20,
    },
    card: {
        width: 360,
        height: 160,
        backgroundColor: '#004A2B',
        borderRadius: 35,
        marginBottom: 40,
        alignSelf: 'center',
        flexDirection: 'row',
        padding: 10,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 8 },
        shadowOpacity: 0.8,
        shadowRadius: 0,
        elevation: 4,
    },
    containerImage: {
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: '#1B5B44',
        width: 196,
        height: 138,
        borderRadius: 30,
        marginRight: 20,
        overflow: 'hidden',
    },
    image: {
        width: '100%',
        height: '100%',
        borderRadius: 20,
    },
    textButtonContainer: {
        justifyContent: 'center',
        alignItems: 'center',
        flex: 1,
    },
    cardText: {
        color: 'white',
        fontSize: 18,
        fontFamily: 'Quicksand',
        textAlign: 'center',
    },
    containerButton: {
        width: 80,
        height: 55,
        marginTop: 10,
        padding: 10,
        borderRadius: 30,
        justifyContent: 'center',
        alignItems: 'center',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 7 },
        shadowOpacity: 0.8,
        shadowRadius: 4,
        elevation: 5,
    },
});