import { StyleSheet, Dimensions } from 'react-native';
import { RFPercentage } from 'react-native-responsive-fontsize';

// Obtener dimensiones de la pantalla
const { width, height } = Dimensions.get('window');

// Definir una proporción base para escalar elementos (basada en un ancho de diseño de 414px)
const scale = width / 414;

// Ajustar ITEM_WIDTH para que sea responsivo (originalmente 200px en un diseño de 414px)
const ITEM_WIDTH = 200 * scale;

export const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#FEE6C4',
        justifyContent: 'space-between',
    },
    header: {
        backgroundColor: '#FFA851',
        height: height * 0.20,
        borderBottomLeftRadius: 15 * scale,
        borderBottomRightRadius: 15 * scale,
        justifyContent: 'center',
        alignItems: 'center',
    },
    textHeader: {
        fontSize: RFPercentage(5),
        color: 'white',
        fontFamily: 'Quicksand',
        textAlign: 'center',
    },
    menuButton: {
        backgroundColor: 'black',
        borderRadius: 70 * scale,
        width: 50 * scale,
        height: 50 * scale,
        justifyContent: 'center',
        alignItems: 'center',
        marginRight: 10 * scale,
    },
    containerEmotion: {
        backgroundColor: '#6d3709',
        borderRadius: 80 * scale,
        width: 60 * scale,
        height: 60 * scale,
        justifyContent: 'center',
        alignItems: 'center',
        marginLeft: 10 * scale,
        zIndex: 1,
    },
    Emotion: {
        backgroundColor: '#f4d880',
        borderRadius: 60 * scale,
        width: 50 * scale,
        height: 50 * scale,
        justifyContent: 'center',
        alignItems: 'center',
        marginLeft: 20 * scale,
        zIndex: 1,
        position: 'absolute',
    },
    containerBarEmotion: {
        backgroundColor: '#6d3709',
        borderTopRightRadius: 60 * scale,
        borderBottomRightRadius: 60 * scale,
        width: width * 0.6,
        height: 35 * scale,
        justifyContent: 'center',
        alignItems: 'flex-start',
        marginLeft: -10 * scale,
        overflow: 'hidden',
    },
    BarEmotion: {
        backgroundColor: 'orange',
        borderTopRightRadius: 60 * scale,
        borderBottomRightRadius: 60 * scale,
        height: 25 * scale,
        justifyContent: 'center',
        alignItems: 'center',
        marginLeft: -10 * scale,
        position: 'relative',
    },
    scrollArea: {
        flex: 1,
        marginTop: 20 * scale,
        marginBottom: 40 * scale,
    },
    scrollContainer: {
        paddingHorizontal: 10 * scale,
        paddingBottom: 20 * scale,
    },
    Card: {
        width: width * 0.9,
        height: 160 * scale,
        backgroundColor: '#E26F02',
        borderRadius: 35 * scale,
        marginBottom: 40 * scale,
        alignSelf: 'center',
        flexDirection: 'row',
        padding: 10 * scale,
    },
    containerImage: {
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: '#EC8926',
        width: width * 0.45,
        height: 138 * scale,
        borderRadius: 30 * scale,
        marginRight: 20 * scale,
    },
    image: {
        width: 50 * scale,
        height: 50 * scale,
        resizeMode: 'contain',
    },
    textButtonContainer: {
        justifyContent: 'center',
        alignItems: 'center',
        flex: 1,
    },
    cardText: {
        color: 'white',
        fontSize: RFPercentage(2.5),
        fontFamily: 'Quicksand',
        textAlign: 'center',
    },
    containerButton: {
        width: 80 * scale,
        height: 55 * scale,
        marginTop: 10 * scale,
        padding: 10 * scale,
        borderRadius: 30 * scale,
        justifyContent: 'center',
        alignItems: 'center',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 7 * scale },
        shadowOpacity: 0.8,
        shadowRadius: 4 * scale,
        elevation: 5,
    },
    buttonText: {
        color: 'white',
        fontWeight: 'bold',
    },
    containerShop: {
        flex: 1,
        alignItems: 'center',
        marginTop: 10 * scale,
    },
    containerOption: {
        alignItems: 'center',
    },
    textOption: {
        marginBottom: 10 * scale,
        fontSize: 24 * scale,
        fontFamily: 'Quicksand',
        color: 'black',
        textAlign: 'center',
    },
    Option: {
        flexDirection: 'row',
        justifyContent: 'center',
        alignItems: 'center',
    },
    flatListContainer: {
        width: ITEM_WIDTH,
        overflow: 'hidden',
        marginHorizontal: 20 * scale,
    },
    containerCircleFood: {
        width: ITEM_WIDTH,
        height: ITEM_WIDTH,
        borderRadius: ITEM_WIDTH / 2,
        backgroundColor: '#6d3709',
        justifyContent: 'center',
        alignItems: 'center',
    },
    imageFood: {
        width: ITEM_WIDTH - (20 * scale),
        height: ITEM_WIDTH - (20 * scale),
        resizeMode: 'contain',
        borderRadius: (ITEM_WIDTH - (20 * scale)) / 2,
    },
    containerInfo: {
        marginTop: '3%',
        width: '90%',
        height: '20%',
        backgroundColor: '#E97B36',
        borderRadius: 20 * scale,
        justifyContent: 'center',
        alignItems: 'center',
    },
    info: {
        marginTop: '3%',
        width: '90%',
        height: '20%',
        borderRadius: 20 * scale,
        borderWidth: 7 * scale,
        borderColor: '#994c00',
        backgroundColor: '#ffc78f',
        flexDirection: 'row',
        justifyContent: 'space-evenly',
        alignItems: 'center',
    },
    precio: {
        width: '30%',
        height: '50%',
        backgroundColor: '#D78B49',
        borderRadius: 20 * scale,
        flexDirection: 'row',
        alignItems: 'center',
    },
    coin: {
        width: 40 * scale,
        height: 40 * scale,
        backgroundColor: 'orange',
        borderRadius: 20 * scale,
    },
    textPrecio: {
        color: 'black',
        fontSize: 15 * scale,
        fontFamily: 'Quicksand_Medium',
        marginLeft: 7 * scale,
    },
    cantidad: {
        flexDirection: 'row',
        alignItems: 'center',
        marginHorizontal: 10 * scale,
    },
    textCantidad: {
        color: 'black',
        fontSize: 25 * scale,
        fontFamily: 'Quicksand',
        marginHorizontal: 10 * scale,
    },
    buttonComprar: {
        width: '30%',
        height: '50%',
        backgroundColor: '#8A460B',
        borderRadius: 20 * scale,
        justifyContent: 'center',
        alignItems: 'center',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 4 * scale },
        shadowOpacity: 0.8,
        shadowRadius: 0,
        elevation: 4,
    },
    textComprar: {
        color: 'white',
        fontSize: 15 * scale,
        fontFamily: 'Quicksand_Medium',
    },
    containerInventary: {
        width: '100%',
        height: '25%', // Restaurado y confirmado como proporción original
        backgroundColor: '#EBD2B2',
        borderTopLeftRadius: 20 * scale,
        borderTopRightRadius: 20 * scale,
        alignSelf: 'center',
        flexDirection: 'column',
    },
    containerButtonAlimentar: {
        height: height * 0.07,
    },
    buttonAlimentar: {
        top: -20 * scale,
        width: '60%',
        height: '90%',
        backgroundColor: '#C16718',
        borderRadius: 30 * scale,
        justifyContent: 'center',
        alignItems: 'center',
        alignSelf: 'center',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 4 * scale },
        shadowOpacity: 0.8,
        shadowRadius: 0,
        elevation: 4,
    },
    textButtonAlimentar: {
        color: 'white',
        fontSize: RFPercentage(3.5),
        fontFamily: 'Quicksand',
    },
    containerFood: {
        flex: 1,
        alignItems: 'center',
    },
    containerItems: {
        width: '90%',
        height: '70%', // Ajustado a 70% para dar más espacio a los ítems
        backgroundColor: '#FF973D',
        borderRadius: 20 * scale,
    },
    containerPrecio: {
        backgroundColor: 'black',
        display: 'flex',
        bottom: -10 * scale,
        position: 'absolute',
        width: 50 * scale,
        height: 50 * scale,
        bottom: 0,
    },
    textFood: {
        marginTop: 10 * scale,
        color: 'black',
        fontSize: RFPercentage(3.5),
        fontFamily: 'Quicksand',
        textAlign: 'center',
    },
    itemsContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        marginHorizontal: 15 * scale,
    },
    itemContainer: {
        alignItems: 'center',
    },
    item: {
        width: 50 * scale, // Reducido a 50 para un tamaño más cercano al original
        height: 50 * scale, // Reducido a 50 para un tamaño más cercano al original
        borderRadius: 25 * scale,
        backgroundColor: 'transparent',
        justifyContent: 'center',
        alignItems: 'center',
        zIndex: 10,
    },
    priceTab: {
        marginTop: '20%',
        backgroundColor: '#d16a00',
        width: '80%',
        height: '50%',
        borderRadius: 10 * scale,
        justifyContent: 'center',
        alignItems: 'center',
        borderColor: '#d16a00',
        borderWidth: 5 * scale,
        zIndex: 1,
    },
    priceText: {
        color: 'white',
        fontSize: 10 * scale, // Reducido para mantener proporción
        fontWeight: 'bold',
    },
    arrowButton: {
        width: 40 * scale,
        height: 40 * scale,
        justifyContent: 'center',
        alignItems: 'center',
    },
});